import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/header";
import Footer from "@/components/footer";
import React from "react";
import { getPopularMovies } from "@/api";
import { Movie } from "@/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const popularPromise = getPopularMovies();
  // const { results: popularMovies } = await popularPromise;
  // const bgPosterPath = popularMovies.map((movie: Movie) => movie.poster_path);
  // console.log(bgPosterPath);
  // const index = Math.floor(Math.random() * 20);
  // const ımage = `https://image.tmdb.org/t/p/original${bgPosterPath[index]}`;

  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "text-base flex flex-col ml-10 mr-10 bg-no-repeat bg-cover bg-center  "
        )}
        // style={{
        //   backgroundImage: `url(${ımage})`,
        // }}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
