import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/header";
import React from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "text-base flex flex-col ml-10 mr-10 bg-no-repeat bg-cover bg-center  "
        )}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
